<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Credit Card Security</name>
   <tag></tag>
   <elementGuidId>b3251ae3-0313-41b1-805b-2c5915b99ddf</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/security</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu__link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-link-system-path</name>
      <type>Main</type>
      <value>node/184</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Credit Card Security</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js js csstransforms3d&quot;]/body[@class=&quot;page--node-185 user-logged-out path--node page--node-type-paragraphs-page&quot;]/div[@class=&quot;outline-main -dom-ready&quot;]/div[@class=&quot;-business&quot;]/footer[1]/div[@class=&quot;footer-links&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row -margin-none&quot;]/div[@class=&quot;col -seventwelfths right&quot;]/div[@class=&quot;col show-in-mobile&quot;]/ul[@class=&quot;menu menu--footer-right menu--level-0 menu--root&quot;]/li[@class=&quot;menu__item&quot;]/a[@class=&quot;menu__link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
